Repository framgia/sph-hris, pull requests merged in 2023-02, with the labels that each got.

#51 HRIS-74 [Markup] Create My Leaves Page
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/pages/my-leaves.tsx
Labels: For Code Review 💻

#54 HRIS-82 [BE] Implement Edit time entry functionality
  api/Program.cs
  api/Requests/TimeEntryRequest.cs
  api/Schema/Mutations/TimeEntryMutation.cs
  api/Services/TimeSheetService.cs
Labels: For Code Review 💻

#52 HRIS-78 [Markup] Create List of Leaves tabbed page in Leave Management
  client/src/components/atoms/Buttons/ButtonLink.tsx
  client/src/components/atoms/TabLink/index.tsx
  client/src/components/molecules/ListOfLeaveTable/DesktopTable.tsx
  client/src/components/molecules/ListOfLeaveTable/MobileDisclose.tsx
  client/src/components/molecules/ListOfLeaveTable/ShowReasonModal.tsx
  client/src/components/molecules/ListOfLeaveTable/columns.tsx
  client/src/components/molecules/ListOfLeaveTable/index.tsx
  client/src/components/molecules/SummaryFilterDropdown/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/templates/FilterDropdownTemplate/index.tsx
  client/src/components/templates/LeaveManagementLayout/index.tsx
  client/src/pages/leave-management/list-of-leave.tsx
  client/src/utils/constants/dummyListOfLeaveData.ts
  client/src/utils/interfaces/index.tsx
Labels: For Code Review 💻

#55 HRIS-99 [Markup] Add legends to My DTR page
  client/src/components/organisms/Header/index.tsx
Labels: Approved by Joshua 👌

#61 HRIS-83 [FE] Integrate Edit time entry functionality
  api/Services/TimeSheetService.cs
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/EditTimeEntryModal/index.tsx
  client/src/graphql/mutations/timeEntryMutation.ts
  client/src/hooks/useTimeEntryMutation.ts
Labels: For Code Review 💻

#59 HRIS-84 [BE] Implement Fetch Leave Data for the in My Leaves Page functionality
  api/DTOs/HeatMapDTO.cs
  api/DTOs/LeaveBreakdownDTO.cs
  api/DTOs/LeaveHeatMapDTO.cs
  api/DTOs/LeavesDTO.cs
  api/DTOs/LeavesTableDTO.cs
  api/Enums/LeaveTypeEnum.cs
  api/Schema/Queries/LeaveQuery.cs
  api/Services/LeaveService.cs
Labels: For Code Review 💻

#62 HRIS-83-01 [FE] Fix: Disabled time fields if there are no initial data
  client/src/components/molecules/EditTimeEntryModal/index.tsx
Labels: For Code Review 💻

#63 HRIS-85 [FE] Integrate Fetch Leave Data for the in My Leaves Page functionality
  client/src/components/molecules/BreakdownOfLeavesCard/index.tsx
  client/src/components/molecules/LeaveManagementResultTable/Table.tsx
  client/src/components/molecules/LeaveManagementResultTable/columns.tsx
  client/src/components/molecules/LeaveManagementResultTable/index.tsx
  client/src/graphql/queries/leaveQuery.ts
  client/src/hooks/useLeave.ts
  client/src/pages/leave-management/leave-summary.tsx
  client/src/pages/leave-management/yearly-summary.tsx
  client/src/pages/my-leaves.tsx
  client/src/utils/constants/leaveTypes.ts
  client/src/utils/generateData.ts
  client/src/utils/getLeaveType.ts
  client/src/utils/types/leaveTypes.ts
Labels: For Code Review 💻

#65 HRIS-90 [BE] Implement Fetch Yearly Summary data of all employees functionality
  api/DTOs/HeatMapDTO.cs
  api/DTOs/LeaveHeatMapDTO.cs
  api/DTOs/LeavesDTO.cs
  api/Schema/Queries/LeaveQuery.cs
  api/Services/LeaveService.cs
Labels: For Code Review 💻

#67 HRIS-78-01 [Markup] Create List of Leaves tabbed page in Leave Management
  client/src/components/templates/LeaveManagementLayout/index.tsx
Labels: For Code Review 💻

#66 HRIS-87 [FE] Implement and Integrate filter functionality in my leaves page
  client/src/components/molecules/LeaveManagementResultTable/index.tsx
  client/src/components/molecules/SummaryFilterDropdown/index.tsx
  client/src/hooks/useLeave.ts
  client/src/pages/my-leaves.tsx
Labels: For Code Review 💻

#68 HRIS-91 [FE] Integrate Fetch Yearly Summary data of all employees functionality
  client/src/components/molecules/SummaryFilterDropdown/index.tsx
  client/src/graphql/queries/leaveQuery.ts
  client/src/hooks/useLeave.ts
  client/src/pages/leave-management/yearly-summary.tsx
  client/src/utils/generateData.ts
  client/src/utils/types/leaveTypes.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#69 HRIS-93 [FE] Integrate fetch all requested leaves functionality
  api/Migrations/20230203074010_UpdateLeaveSeeder.Designer.cs
  api/Migrations/20230203074010_UpdateLeaveSeeder.cs
  api/Seeders/DatabaseSeeder.cs
  api/Services/LeaveService.cs
  client/src/components/molecules/ListOfLeaveTable/columns.tsx
  client/src/graphql/queries/leaveQueries.ts
  client/src/hooks/useLeaveQuery.ts
  client/src/pages/leave-management/list-of-leave.tsx
  client/src/utils/types/leaveTypes.ts
Labels: Approved and Merged ✔️

#70 HRIS-81 [FE] Integrate File Leave Request Functionality
  api/Program.cs
  api/Requests/CreateLeaveRequest.cs
  api/Schema/Queries/LeaveQuery.cs
  api/Schema/Queries/UserQuery.cs
  api/Services/LeaveService.cs
  api/Services/UserService.cs
  client/package-lock.json
  client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx
  client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx
  client/src/graphql/mutations/leaveMutation.ts
  client/src/graphql/queries/UserQuery.ts
  client/src/graphql/queries/leaveQuery.ts
  client/src/graphql/queries/projectQuery.ts
  client/src/hooks/useLeave.ts
  client/src/hooks/useProject.ts
  client/src/hooks/useUserQuery.ts
  client/src/utils/constants/roles.ts
  client/src/utils/createLeaveHelpers.ts
  client/src/utils/types/formValues.ts
  client/src/utils/types/leaveTypes.ts
  client/src/utils/types/projectTypes.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#71 HRIS-93-01 [FE] Fix: Set the decimal places on Total Undertime and Leaves to 3
  client/src/pages/leave-management/list-of-leave.tsx
Labels: For Code Review 💻

#73 HRIS-89 [FE] Implement and Integrate Fetch Leave Summary data of a specific employee functionality
  api/Schema/Queries/UserQuery.cs
  client/src/components/molecules/SummaryFilterDropdown/index.tsx
  client/src/components/templates/FilterDropdownTemplate/index.tsx
  client/src/hooks/useLeave.ts
  client/src/hooks/useUserQuery.ts
  client/src/pages/leave-management/leave-summary.tsx
  client/src/pages/leave-management/yearly-summary.tsx
  client/src/pages/my-leaves.tsx
  client/src/utils/maps/filterOptions.ts
  client/src/utils/types/userTypes.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#72 HRIS-96 [BE] Implement Remaining Paid Leaves functionality
  api/Entities/User.cs
  api/Migrations/20230207043905_ModifyUsers.Designer.cs
  api/Migrations/20230207043905_ModifyUsers.cs
  api/Schema/Queries/LeaveQuery.cs
  api/Services/LeaveService.cs
Labels: For Code Review 💻

#75 HRIS-97 [FE] Integrate Remaining Paid Leaves functionality
  client/src/components/templates/LeaveManagementLayout/index.tsx
  client/src/graphql/queries/leaveQueries.ts
  client/src/hooks/useLeaveQuery.ts
  client/src/pages/my-leaves.tsx
Labels: Approved by Joshua 👌, For Code Review 💻

#81 HRIS-107 [BugTask] Remove Filter markup and implement search function
  client/src/components/templates/LeaveManagementLayout/index.tsx
  client/src/pages/leave-management/list-of-leave.tsx
Labels: For Code Review 💻

#83 HRIS-108 [BugTask] Remaining Paid Leave should change base on the filter
  api/DTOs/LeavesDTO.cs
  api/Services/LeaveService.cs
  client/src/components/templates/LeaveManagementLayout/index.tsx
  client/src/graphql/queries/leaveQuery.ts
  client/src/utils/types/leaveTypes.ts
Labels: For Code Review 💻

#86 HRIS-102-01 [BE] Fix: Modified avatarLink generation to work on docker
  api/DTOs/UserDTO.cs
  api/Program.cs
  api/Services/HttpContextService.cs
  api/Services/TimeInService.cs
Labels: For Code Review 💻

#85 HRIS-108-01 [BugTask] Apply Three Decimal Place
  client/src/components/templates/Layout/index.tsx
  client/src/components/templates/LeaveManagementLayout/index.tsx
Labels: For Code Review 💻

#79 HRIS-100 [BugTask] Error implement the Download function
  api/.gitignore
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
  client/next.config.js
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/ListOfLeaveTable/columns.tsx
  client/src/components/organisms/TimeInDrawer/index.tsx
  client/src/components/organisms/TimeOutDrawer/index.tsx
  client/src/components/organisms/ViewDetailsDrawer/index.tsx
  client/src/components/organisms/WorkInterruptionDrawer/index.tsx
  client/src/graphql/queries/leaveQueries.ts
  client/src/graphql/queries/timesheetQueries.ts
  client/src/hooks/useTimesheetQuery.ts
  client/src/pages/_document.tsx
  client/src/pages/leave-management/list-of-leave.tsx
  client/src/utils/constants/dummyListOfLeaveData.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/leaveTypes.ts
  client/src/utils/types/timeEntryTypes.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#88 HRIS-110 [BugTask] User should able to click Time in or out column in the My DTR and DTR Management
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
Labels: For Code Review 💻

#78 HRIS-103 [Markup] Create My Overtime Page
  client/src/components/molecules/MyOvertimeTable/Chip.tsx
  client/src/components/molecules/MyOvertimeTable/DesktopTable.tsx
  client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
  client/src/components/molecules/MyOvertimeTable/ShowRemarksModal.tsx
  client/src/components/molecules/MyOvertimeTable/YearlyFilterDropdown.tsx
  client/src/components/molecules/MyOvertimeTable/columns.tsx
  client/src/components/molecules/MyOvertimeTable/index.tsx
  client/src/components/templates/ModalTemplate/ModalHeader.tsx
  client/src/pages/my-overtime.tsx
  client/src/utils/constants/dummyAddNewLeaveFields.ts
  client/src/utils/constants/dummyMyOvertimeData.ts
  client/src/utils/constants/overtimeStatus.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#80 HRIS-104 [Markup] Create File for Overtime Modal
  client/src/components/molecules/AddNewOvertimeModal/index.tsx
  client/src/components/molecules/MyOvertimeTable/columns.tsx
  client/src/pages/my-overtime.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#89 HRIS-106 [Markup] Create Overtime Management Page for Manager
  client/src/components/molecules/NavList/index.tsx
  client/src/components/molecules/OvertimeManagementTable/ApproveConfirmationModal.tsx
  client/src/components/molecules/OvertimeManagementTable/DesktopTable.tsx
  client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
  client/src/components/molecules/OvertimeManagementTable/ShowRemarksModal.tsx
  client/src/components/molecules/OvertimeManagementTable/UpdateOvertimeModal.tsx
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
  client/src/components/molecules/OvertimeManagementTable/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/pages/overtime-management.tsx
  client/src/utils/constants/dummyOvertimeManagementData.ts
  client/src/utils/constants/sidebarMenu.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/styles/tailwind.css
Labels: For Code Review 💻

#93 HRIS-124 [Markup] Modify File Leave/Undertime Request Modal
  client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx
  client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx
  client/src/components/molecules/AddNewLeaveModal/index.tsx
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
  client/src/utils/constants/dummyAddNewLeaveFields.ts
  client/src/utils/constants/leaveTypes.ts
  client/src/utils/constants/numberOfDaysInLeaves.ts
  client/src/utils/createLeaveHelpers.ts
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: Approved by Arden ✅, For Code Review 💻

#87 HRIS-98 [Markup] Create Notification Page Markup
  client/package-lock.json
  client/src/components/molecules/NotificationFilterDropdown/index.tsx
  client/src/components/molecules/NotificationList/NotificationItem.tsx
  client/src/components/molecules/NotificationList/columns.tsx
  client/src/components/molecules/NotificationList/index.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/pages/notifications.tsx
  client/src/utils/constants/dummyNotificationData.ts
  client/src/utils/interfaces/index.tsx
Labels: Approved by Arden ✅, Approved by Joshua 👌, For Code Review 💻

#95 HRIS-125 [BugTask] Change table to accordion in My leave, Yearly summary and Leave summary
  client/src/components/molecules/BreakdownOfLeavesCard/index.tsx
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
  client/src/components/molecules/LeaveManagementResultTable/MobileDisclose.tsx
  client/src/components/molecules/LeaveManagementResultTable/index.tsx
  client/src/components/molecules/ListOfLeaveTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
  client/src/components/molecules/NotificationList/NotificationItem.tsx
  client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/pages/_document.tsx
  client/src/pages/leave-management/leave-summary.tsx
  client/src/pages/leave-management/yearly-summary.tsx
  client/src/pages/my-leaves.tsx
  client/src/utils/generateData.ts
  client/tailwind.config.js
Labels: For Code Review 💻

#96 HRIS-126 [Markup] Create Employee Management Page
  client/src/components/molecules/EmployeeManagementTable/DesktopTable.tsx
  client/src/components/molecules/EmployeeManagementTable/MobileDisclose.tsx
  client/src/components/molecules/EmployeeManagementTable/columns.tsx
  client/src/components/molecules/EmployeeManagementTable/index.tsx
  client/src/pages/employee-management.tsx
  client/src/utils/constants/dummyEmployeeManagement.ts
  client/src/utils/interfaces/index.tsx
Labels: For Code Review 💻

#97 HRIS-122 [FE] Integrate Send notification when filing a leave request functionality
  api/Enums/InputValidationMessageEnum.cs
  api/Requests/CreateLeaveRequest.cs
  api/Services/LeaveService.cs
  api/Services/NotificationService.cs
  api/Utils/Validation.cs
  client/package-lock.json
  client/package.json
  client/src/components/molecules/AddNewLeaveModal/LeaveTab.tsx
  client/src/components/molecules/AddNewLeaveModal/UndertimeTab.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/subscriptions/leaveSubscription.ts
  client/src/pages/sign-in.tsx
  client/src/utils/constants/dummyAddNewLeaveFields.ts
  client/src/utils/createLeaveHelpers.ts
  client/src/utils/types/formValues.ts
  client/src/utils/types/leaveTypes.ts
Labels: For Code Review 💻

#91 HRIS-100-01 [FE] Fix: Download button functionality
  api/DTOs/SpecificTimeDTO.cs
  api/Program.cs
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
  client/src/components/organisms/ViewDetailsDrawer/index.tsx
  client/src/graphql/queries/timesheetQueries.ts
  client/src/utils/types/timeEntryTypes.ts
Labels: Approved by Arden ✅, For Code Review 💻

#101 HRIS-127 [Markup] Create Add Employee Modal
  client/src/components/molecules/AddNewEmployeeModal/index.tsx
  client/src/pages/employee-management.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#102 HRIS-123 [FE] Implement Fetch notifications for the authenticated user functionality
  api/Services/LeaveService.cs
  api/Services/NotificationService.cs
  api/Services/UserService.cs
  client/src/components/molecules/NotificationList/NotificationItem.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/queries/NotificationQueries.ts
  client/src/graphql/queries/leaveQueries.ts
  client/src/hooks/useNotificationQuery.ts
  client/src/pages/leave-management/list-of-leave.tsx
  client/src/pages/notifications.tsx
  client/src/utils/constants/dummyNotificationData.ts
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/leaveTypes.ts
  client/src/utils/types/notificationTypes.ts
Labels: For Code Review 💻

#103 HRIS-123-01 [FE] Fixed routing from Leave Management pages to Notifications page
  api/Seeders/DatabaseSeeder.cs
  client/src/components/molecules/NotificationPopOver/index.tsx
Labels: For Code Review 💻

#100 HRIS-121 [FE] Fetch all notifications and display on to the dropdown
  api/Program.cs
  api/Requests/NotificationRequest.cs
  api/Schema/Mutations/NotificationMutation.cs
  api/Schema/Queries/NotificationQuery.cs
  api/Services/NotificationService.cs
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/mutations/notificationMutation.ts
  client/src/graphql/queries/NotificationQueries.ts
  client/src/hooks/useNotificationMutation.ts
  client/src/hooks/useNotificationQuery.ts
  client/src/pages/notifications.tsx
  client/src/utils/constants/dummyNotificationData.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/notificationTypes.ts
Labels: For Code Review 💻

#104 HRIS-134 [FE] Implement Filter notifications functionality
  client/src/components/molecules/NotificationFilterDropdown/index.tsx
  client/src/pages/notifications.tsx
  client/src/utils/constants/notificationFilter.ts
Labels: For Code Review 💻
