Repository framgia/sph-hris, pull requests merged in 2023-01, with the labels that each got.

#1 [Markup] Create Page Layout for Authenticated User
  client/.eslintrc.js
  client/.prettierrc
  client/.vscode/settings.json
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/postcss.config.js
  client/public/images/maintenance.png
  client/public/images/under-construction.png
  client/public/sun-color-icon.svg
  client/src/components/atoms/Avatar/index.tsx
  client/src/components/atoms/Buttons/Button.tsx
  client/src/components/atoms/Buttons/ButtonLink.tsx
  client/src/components/atoms/Logo/index.tsx
  client/src/components/atoms/Text/index.tsx
  client/src/components/molecules/NavList/NavItem.tsx
  client/src/components/molecules/NavList/index.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/pages/MaintenancePage/index.tsx
  client/src/components/pages/UnderContructionPage/index.tsx
  client/src/components/templates/Layout/index.tsx
  client/src/components/templates/MenuTransition/index.tsx
  client/src/components/templates/PopoverTransition/index.tsx
  client/src/graphql/.rm
  client/src/hooks/.rm
  client/src/lib/.rm
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/dtr-management.tsx
  client/src/pages/employee-management.tsx
  client/src/pages/index.tsx
  client/src/pages/leave-management.tsx
  client/src/pages/my-daily-time-record.tsx
  client/src/pages/my-leaves.tsx
  client/src/pages/my-overtime.tsx
  client/src/pages/overtime-management.tsx
  client/src/pages/schedule-management.tsx
  client/src/utils/FeatherRenderIcon.tsx
  client/src/utils/constants/index.ts
  client/src/utils/handleImageError.tsx
  client/src/utils/icons/BreakIcon.tsx
  client/src/utils/icons/ClockInIcon.tsx
  client/src/utils/icons/ClockOutIcon.tsx
  client/src/utils/icons/MyOvertimeIcon.tsx
  client/src/utils/interfaces/index.tsx
  client/src/utils/jsons/.rm
  client/src/utils/styles/globals.css
  client/src/utils/styles/tailwind.css
  client/src/utils/types/.rm
  client/src/utils/validation/.rm
  client/src/utils/windstitchUtils.ts
  client/styles/globals.css
  client/tailwind.config.js
  client/tsconfig.json
Labels: For Code Review 💻

#3 [HRIS-26] - [Dev] Setup GitHub Actions
  .github/workflows/actions.yml
  api/.editorconfig
  client/.eslintignore
  client/.eslintrc.js
  client/.prettierignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/pages/api/hello.ts
Labels: For Code Review 💻

#8 HRIS-18 [BE] Create time out functionality
  api/Program.cs
  api/Requests/TimeOutRequest.cs
  api/Schema/Mutations/TimeOutMutation.cs
  api/Services/TimeOutService.cs
Labels: For Code Review 💻

#9 HRIS-28 [Markup] Create Drawer Markup
  client/package-lock.json
  client/package.json
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/TimeInDrawer/index.tsx
  client/src/components/organisms/TimeOutDrawer/index.tsx
  client/src/components/templates/DrawerTemplate/index.tsx
  client/src/components/templates/Layout/index.tsx
Labels: For Code Review 💻

#4 HRIS-23 [Markup] Create Timesheet Table for all employees Markup
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Buttons/ButtonLink.tsx
  client/src/components/atoms/Chip/index.tsx
  client/src/components/atoms/RadioButton/index.tsx
  client/src/components/atoms/Text/index.tsx
  client/src/components/molecules/DTRManagementTable/DesktopTable.tsx
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/DTRManagementTable/index.tsx
  client/src/components/molecules/FooterTable/PageCount.tsx
  client/src/components/molecules/FooterTable/Pagination.tsx
  client/src/components/molecules/FooterTable/index.tsx
  client/src/components/molecules/GlobalSearchFilter/index.tsx
  client/src/components/molecules/LegendTooltip/index.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/molecules/SummaryMenuDropdown/index.tsx
  client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/TimeInDrawer/index.tsx
  client/src/components/organisms/TimeOutDrawer/index.tsx
  client/src/components/templates/Layout/index.tsx
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
  client/src/pages/api/hello.ts
  client/src/pages/dtr-management.tsx
  client/src/pages/index.tsx
  client/src/utils/constants/index.ts
  client/src/utils/fuzzyFilter.ts
  client/src/utils/handleImageError.tsx
  client/src/utils/icons/FilterIcon.tsx
  client/src/utils/icons/SortIcon.tsx
  client/src/utils/interfaces/index.tsx
  client/src/utils/styles/tailwind.css
  client/src/utils/windstitchUtils.ts
  client/tailwind.config.js
Labels: Approved and Merged ✔️

#16 HRIS-12 [FE] Integrate login functionality
  api/Program.cs
  api/Schema/Mutations/SigninMutation.cs
  api/Seeders/DatabaseSeeder.cs
  api/Services/SigninService.cs
  api/api.csproj
  client/package-lock.json
  client/package.json
  client/src/graphql/mutations/signInMutation.ts
  client/src/hooks/useSignInMutation.ts
  client/src/middleware.ts
  client/src/pages/_app.tsx
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/sign-in.tsx
  client/src/utils/shared/client.ts
Labels: For Code Review 💻

#18 HRIS-14 [FE] Integration logout functionality
  api/Program.cs
  api/Requests/LogoutRequest.cs
  api/Schema/Mutations/LogoutMutation.cs
  api/Services/LogoutService.cs
  client/.gitignore
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/graphql/mutations/logOutMutation.ts
  client/src/hooks/useLogOutMutation.ts
  client/src/pages/index.tsx
  client/src/pages/sign-in.tsx
  client/src/utils/ssr.ts
Labels: For Code Review 💻

#17 HRIS-21 [BE] Create get timesheet functionality
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
Labels: For Code Review 💻

#20 HRIS-29 [BugTask] DTR Management Deformation
  client/src/components/molecules/FooterTable/index.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/pages/dtr-management.tsx
  client/src/utils/mapping/dtrManagementMap.tsx
Labels: For Code Review 💻

#19 HRIS-22 [FE] Integrate timesheet table functionality
  api/Program.cs
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
  client/package-lock.json
  client/src/components/molecules/DTRManagementTable/DesktopTable.tsx
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/DTRManagementTable/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/queries/timesheetQueries.ts
  client/src/hooks/useTimesheetQuery.ts
  client/src/pages/dtr-management.tsx
  client/src/pages/my-daily-time-record.tsx
  client/src/utils/fuzzyFilter.ts
  client/src/utils/icons/BarsLoadingIcon.tsx
  client/src/utils/mapping/dtrManagementMap.tsx
  client/src/utils/types/timeEntryTypes.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#21 HRIS-40 [BE] Implement GET specific Time Entry functionality
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
Labels: Approved by Joshua 👌, For Code Review 💻

#24 HRIS-50 [Markup] Create Work Interruption Drawer Markup
  client/package-lock.json
  client/package.json
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/WorkInterruptionDrawer/index.tsx
  client/src/components/templates/Layout/index.tsx
  client/src/utils/styles/tailwind.css
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#25 HRIS-56 [BE] Implement GET list of work interruptions for a specific employee functionality
  api/DTOs/WorkInterruptionDTO.cs
  api/Program.cs
  api/Requests/ShowInterruptionRequest.cs
  api/Schema/Mutations/InterruptionMutation.cs
  api/Schema/Queries/InterruptionQuery.cs
  api/Services/InterruptionService.cs
  client/next.config.js
  client/src/middleware.ts
  client/src/pages/api/auth/[...nextauth].ts
Labels: Approved by Joshua 👌

#28 HRIS-48 [BE] Implement GET data based on the filter options
  api/DTOs/TimeEntryDTO.cs
  api/Requests/TimesheetRequest.cs
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
Labels: For Code Review 💻

#29 HRIS-60 [FE] Integrate file work interruption request functionality
  api/Requests/CreateInterruptionRequest.cs
  api/Schema/Queries/InterruptionQuery.cs
  api/Services/InterruptionService.cs
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/WorkInterruptionDrawer/index.tsx
  client/src/graphql/mutations/workInterruptionMutation.ts
  client/src/graphql/queries/workInterruptionQuery.ts
  client/src/hooks/useInterruptionType.ts
  client/src/utils/constants/work-status.ts
  client/src/utils/types/.rm
  client/src/utils/types/formValues.ts
  client/src/utils/types/workInterruptionTypes.ts
  client/src/utils/validation/index.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#27 HRIS-41 [FE] Integrate GET specific Time Entry functionality
  api/DTOs/TimeDTO.cs
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/organisms/TimeInDrawer/index.tsx
  client/src/components/organisms/TimeOutDrawer/index.tsx
  client/src/components/templates/DrawerTemplate/index.tsx
  client/src/graphql/queries/timesheetQueries.ts
  client/src/hooks/useTimesheetQuery.ts
  client/src/utils/types/timeEntryTypes.ts
Labels: For Code Review 💻

#30 HRIS-42 [Markup] Create Drawer which displays the list of downloaded files and remarks of the time entry
  client/src/components/atoms/Alert/index.tsx
  client/src/components/organisms/TimeInDrawer/index.tsx
  client/src/components/organisms/TimeOutDrawer/index.tsx
  client/src/components/organisms/ViewDetailsDrawer/index.tsx
  client/src/components/templates/Layout/index.tsx
Labels: Approved by Joshua 👌, For Code Review 💻

#34 HRIS-43 [BE] Implement GET remarks and uploaded files on the time entry
  api/Services/TimeSheetService.cs
Labels: For Code Review 💻

#33 HRIS-49 [FE] Integrate GET data based on the filter options
  api/Requests/TimesheetRequest.cs
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
  client/src/components/molecules/DTRManagementTable/index.tsx
  client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
  client/src/graphql/queries/timesheetQueries.ts
  client/src/hooks/useTimesheetQuery.ts
  client/src/pages/dtr-management.tsx
Labels: For Code Review 💻

#32 HRIS-53 [BE] Implement Edit and Delete Work Interruption Request functionality
  api/Requests/UpdateInterruptionRequest.cs
  api/Schema/Mutations/InterruptionMutation.cs
  api/Services/InterruptionService.cs
Labels: For Code Review 💻

#35 HRIS-46 [BE] Implement GET summary data functionality
  api/DTOs/TimeEntriesSummaryDTO.cs
  api/DTOs/TimeEntryDTO.cs
  api/Schema/Queries/TimeSheetQuery.cs
  api/Services/TimeSheetService.cs
Labels: For Code Review 💻

#31 HRIS-38 [Markup] Create Work Interruption Modal
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Buttons/ButtonLink.tsx
  client/src/components/atoms/CellHeader/index.tsx
  client/src/components/atoms/Chip/index.tsx
  client/src/components/atoms/RadioButton/index.tsx
  client/src/components/atoms/Text/index.tsx
  client/src/components/molecules/DTRManagementTable/DesktopTable.tsx
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/GlobalSearchFilter/index.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/ShowRemarksModal.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/Table.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/UpdateInterruptionTimeEntriesModal.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/columns.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/index.tsx
  client/src/components/molecules/LegendTooltip/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/templates/ModalTemplate/ModalFooter.tsx
  client/src/components/templates/ModalTemplate/ModalHeader.tsx
  client/src/components/templates/ModalTemplate/index.tsx
  client/src/pages/my-daily-time-record.tsx
  client/src/utils/constants/interruptionDummyTimeEntries.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/styles/globals.css
  client/src/utils/types/formValues.ts
  client/src/utils/validation/.rm
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#36 HRIS-45 [Markup] Create DTR Table Summary Markup
  client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
  client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
  client/src/components/molecules/DTRSummaryTable/columns.tsx
  client/src/components/molecules/DTRSummaryTable/index.tsx
  client/src/components/molecules/SummaryMenuDropdown/index.tsx
  client/src/pages/dtr-management.tsx
  client/src/utils/constants/index.ts
  client/src/utils/interfaces/index.tsx
Labels: Approved and Merged ✔️, Approved by Joshua 👌

#37 HRIS-44 [FE] Integrate GET remarks and uploaded files on the time entry
  client/src/components/organisms/TimeInDrawer/index.tsx
  client/src/components/organisms/TimeOutDrawer/index.tsx
  client/src/components/organisms/ViewDetailsDrawer/index.tsx
  client/src/components/templates/DrawerTemplate/index.tsx
  client/src/graphql/queries/timesheetQueries.ts
  client/src/utils/types/timeEntryTypes.ts
Labels: For Code Review 💻

#40 HRIS-57 [FE] Integrate GET list of work interruptions for a specific employee functionality
  api/DTOs/TimeEntryDTO.cs
  api/DTOs/WorkInterruptionDTO.cs
  client/package-lock.json
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/Table.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/columns.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/templates/ModalTemplate/index.tsx
  client/src/graphql/queries/workInterruptionQuery.ts
  client/src/hooks/useInterruptionType.ts
  client/src/utils/constants/interruptionDummyTimeEntries.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/workInterruptionTypes.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#39 HRIS-47 [FE] Integrate GET summary data functionality
  client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
  client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
  client/src/components/molecules/DTRSummaryTable/columns.tsx
  client/src/components/molecules/DTRSummaryTable/index.tsx
  client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
  client/src/graphql/queries/timesheetQueries.ts
  client/src/hooks/useTimesheetQuery.ts
  client/src/pages/dtr-management.tsx
  client/src/utils/types/timeEntryTypes.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#41 HRIS-47-01 [FE] Fix Mobile view of Summary Table
  client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
  client/src/utils/constants/index.ts
  client/src/utils/interfaces/index.tsx
Labels: Approved and Merged ✔️, Approved by Joshua 👌

#42 HRIS-44-01 [FE] Fix download button and truncate long filenames
  client/src/components/organisms/ViewDetailsDrawer/index.tsx
Labels: Approved and Merged ✔️

#44 HRIS-61 [Bugtask] Url is wrong when logout
  client/src/components/molecules/UserMenuDropdown/index.tsx
  client/src/pages/sign-in.tsx
Labels: Approved by Joshua 👌, For Code Review 💻

#46 HRIS-62 [BugTask] Filter should not reset when refresh
  client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
  client/src/hooks/useTimesheetQuery.ts
  client/src/pages/dtr-management.tsx
Labels: For Code Review 💻

#49 HRIS-64 [BugTask] Integrate dot remarks in mobile view
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
Labels: For Code Review 💻

#48 HRIS-62-01 [BugTask] Search keyword persists on page reload
  client/src/pages/dtr-management.tsx
  client/src/pages/my-daily-time-record.tsx
Labels: Approved by Joshua 👌, For Code Review 💻

#50 HRIS-79 [Markup] Create Leave and Yearly Summary tabbed page in Leave Management
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Alert/index.tsx
  client/src/components/atoms/Buttons/Button.tsx
  client/src/components/atoms/Buttons/ButtonAction.tsx
  client/src/components/atoms/Buttons/ButtonLink.tsx
  client/src/components/atoms/Card/index.tsx
  client/src/components/atoms/MaxWidthContainer/index.tsx
  client/src/components/atoms/RadioButton/index.tsx
  client/src/components/atoms/TabLink/index.tsx
  client/src/components/molecules/BreakdownOfLeavesCard/index.tsx
  client/src/components/molecules/DTRManagementTable/DesktopTable.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
  client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/ShowRemarksModal.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/UpdateInterruptionTimeEntriesModal.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/columns.tsx
  client/src/components/molecules/InterruptionTimeEntriesModal/index.tsx
  client/src/components/molecules/LeaveManagementResultTable/Table.tsx
  client/src/components/molecules/LeaveManagementResultTable/columns.tsx
  client/src/components/molecules/LeaveManagementResultTable/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/NavList/NavItem.tsx
  client/src/components/molecules/NavList/index.tsx
  client/src/components/molecules/SummaryFilterDropdown/index.tsx
  client/src/components/molecules/TimeSheetFilterDropdown/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/organisms/WorkInterruptionDrawer/index.tsx
  client/src/components/templates/DisclosureTransition/index.tsx
  client/src/components/templates/FilterDropdownTemplate/index.tsx
  client/src/components/templates/Layout/index.tsx
  client/src/components/templates/LeaveManagementLayout/index.tsx
  client/src/components/templates/ModalTemplate/index.tsx
  client/src/pages/index.tsx
  client/src/pages/leave-management/leave-summary.tsx
  client/src/pages/leave-management/list-of-leave.tsx
  client/src/pages/leave-management/yearly-summary.tsx
  client/src/pages/my-forms.tsx
  client/src/pages/my-leaves.tsx
  client/src/utils/constants/dummyLeaveSummaryData.ts
  client/src/utils/constants/dummyYearlySummaryData.ts
  client/src/utils/constants/index.ts
  client/src/utils/constants/sidebarMenu.ts
  client/src/utils/generateData.ts
  client/src/utils/icons/FilterIcon.tsx
  client/src/utils/icons/MyOvertimeIcon.tsx
  client/src/utils/icons/SortIcon.tsx
  client/src/utils/interfaces/index.tsx
  client/src/utils/mapping/dtrManagementMap.tsx
  client/src/utils/windstitchUtils.ts
  client/tailwind.config.js
Labels: For Code Review 💻
