Repository framgia/sph-hris, pull requests merged in 2023-03, with the labels that each got.

#98 HRIS-128 [Markup] Create First Day On-boarding Form
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Buttons/ButtonAction.tsx
  client/src/components/atoms/Buttons/ButtonLink.tsx
  client/src/components/atoms/Card/index.tsx
  client/src/components/atoms/CheckBox/index.tsx
  client/src/components/atoms/Logo/index.tsx
  client/src/components/atoms/RadioButton/index.tsx
  client/src/components/molecules/NavList/NavItem.tsx
  client/src/components/molecules/NavList/index.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/molecules/SummaryFilterDropdown/index.tsx
  client/src/components/molecules/UserTimeZone/index.tsx
  client/src/components/organisms/Drawer/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Sidebar/index.tsx
  client/src/components/organisms/TimeInDrawer/index.tsx
  client/src/components/organisms/TimeOutDrawer/index.tsx
  client/src/components/organisms/ViewDetailsDrawer/index.tsx
  client/src/components/organisms/WorkInterruptionDrawer/index.tsx
  client/src/components/templates/MyFormsLayout/index.tsx
  client/src/pages/my-forms.tsx
  client/src/pages/my-forms/atm-applications.tsx
  client/src/pages/my-forms/first-day-onboarding.tsx
  client/src/pages/my-forms/laptop-monitoring.tsx
  client/src/pages/my-forms/personal-information.tsx
  client/src/utils/constants/sidebarMenu.ts
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#107 HRIS-104-01 [Markup] Update File for Overtime Modal
  client/src/components/molecules/AddNewOvertimeModal/index.tsx
  client/src/components/molecules/LegendTooltip/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/OvertimeManagementTable/ApproveConfirmationModal.tsx
  client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
  client/src/components/molecules/OvertimeManagementTable/UpdateOvertimeModal.tsx
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
  client/src/pages/my-overtime.tsx
  client/src/utils/constants/dummyOvertimeManagementData.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#105 HRIS-129 [Markup] Create Personal Information Form
  client/src/pages/my-forms/personal-information.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#110 HRIS-129-1 [Markup] Personal Form Government Validations
  client/src/pages/my-forms/personal-information.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: Approved by Paul Erick :white_check_mark:, For Code Review 💻

#113 HRIS-149 [BE/FE] Implement and Integrate fetch data of filed overtime in the My Overtime Page
  api/Program.cs
  api/Schema/Queries/OvertimeQuery.cs
  api/Services/OvertimeService.cs
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
  client/src/components/molecules/MyOvertimeTable/ShowRemarksModal.tsx
  client/src/components/molecules/MyOvertimeTable/columns.tsx
  client/src/components/molecules/MyOvertimeTable/index.tsx
  client/src/graphql/queries/overtimeQueries.ts
  client/src/hooks/useOvertimeQuery.ts
  client/src/pages/my-overtime.tsx
  client/src/utils/constants/dummyMyOvertimeData.ts
  client/src/utils/myOvertimeHelpers.ts
  client/src/utils/types/overtimeTypes.ts
Labels: Approved by Arden ✅, For Code Review 💻

#114 HRIS-145 [BE] Implement Approve or Disapprove overtime, leave, and undertime functionality
  api/Enums/InputValidationMessageEnum.cs
  api/Enums/NotificationTypeEnum.cs
  api/Enums/ProjectEnum.cs
  api/Program.cs
  api/Requests/ApproveLeaveUndertimeRequest.cs
  api/Requests/ApproveOvertimeRequest.cs
  api/Schema/Mutations/ApprovalMutation.cs
  api/Services/ApprovalService.cs
  api/Services/NotificationService.cs
  api/Utils/Validation.cs
  api/api.csproj
Labels: For Code Review 💻

#118 HRIS-146 [FE] Integrate Approve or Disapprove overtime, leave, and undertime functionality
  api/Services/LeaveService.cs
  api/Services/NotificationService.cs
  api/Services/TimeSheetService.cs
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/NotificationList/NotificationItem.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/mutations/leaveMutation.ts
  client/src/graphql/mutations/overtimeMutation.ts
  client/src/graphql/queries/timesheetQueries.ts
  client/src/hooks/useLeave.ts
  client/src/hooks/useOvertime.ts
  client/src/pages/notifications.tsx
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/notificationHelpers.ts
  client/src/utils/types/leaveTypes.ts
  client/src/utils/types/notificationTypes.ts
  client/src/utils/types/overtimeTypes.ts
  client/src/utils/types/timeEntryTypes.ts
Labels: For Code Review 💻

#119 HRIS-146-01 [FE] Fix Approve/Disapprove of Undertime Requests
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/graphql/mutations/leaveMutation.ts
  client/src/hooks/useLeave.ts
Labels: Approved and Merged ✔️

#120 HRIS-150 [BE/FE] Implement and Integrate filter list be Pending, Approved and Rejected functionality for My Overtime Page
  api/DTOs/MyOvertimeDTO.cs
  api/Schema/Queries/OvertimeQuery.cs
  api/Services/OvertimeService.cs
  client/src/components/molecules/MyOvertimeTable/DesktopTable.tsx
  client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
  client/src/components/molecules/MyOvertimeTable/ShowRemarksModal.tsx
  client/src/components/molecules/MyOvertimeTable/YearlyFilterDropdown.tsx
  client/src/components/molecules/MyOvertimeTable/columns.tsx
  client/src/components/molecules/MyOvertimeTable/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/queries/overtimeQueries.ts
  client/src/hooks/useOvertimeQuery.ts
  client/src/pages/my-overtime.tsx
  client/src/utils/constants/dummyMyOvertimeData.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/myOvertimeHelpers.ts
Labels: For Code Review 💻

#122 HRIS-148 [FE] Integrate approve and disapprove requested overtime for manager functionality
  api/DTOs/OvertimeDTO.cs
  api/Services/ApprovalService.cs
  client/src/components/molecules/AddNewOvertimeModal/index.tsx
  client/src/components/molecules/OvertimeManagementTable/ApproveConfirmationModal.tsx
  client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
  client/src/components/molecules/OvertimeManagementTable/UpdateOvertimeModal.tsx
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
  client/src/hooks/useOvertime.ts
  client/src/pages/overtime-management.tsx
  client/src/utils/constants/dummyOvertimeManagementData.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#121 HRIS-152/HRIS-154 [BE/FE] Implement and Integrate filter list be Pending, Approved and Rejected functionality for HR Admin and Manager Overtime Management Page
  client/src/components/molecules/MyDailyTimeRecordTable/YearlyFilterDropdown.tsx
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
  client/src/components/molecules/OvertimeManagementTable/index.tsx
  client/src/components/templates/FilterDropdownTemplate/index.tsx
  client/src/pages/overtime-management.tsx
Labels: For Code Review 💻

#123 HRIS-151/HRIS-153-01 [BE/FE] Fix overtime management table.
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
Labels: For Code Review 💻

#124 HRIS-153 [BE/FE] Update edit modal and filter out overtime manager
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
  client/src/graphql/queries/overtimeQuery.ts
  client/src/pages/overtime-management.tsx
  client/src/utils/constants/dummyOvertimeManagementData.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/overtimeTypes.ts
Labels: For Code Review 💻

#128 HRIS-160-01 [BE/FE] Fix Overtime Icon display and Scroll in Summary table
  client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
Labels: For Code Review 💻

#111 HRIS-132 [Markup] Create Schedule Management Markup
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Buttons/Button.tsx
  client/src/components/atoms/Buttons/ButtonAction.tsx
  client/src/components/atoms/Buttons/ButtonLink.tsx
  client/src/components/atoms/Buttons/DayButton.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/Li/index.tsx
  client/src/components/atoms/Select/index.tsx
  client/src/components/atoms/TabLink/index.tsx
  client/src/components/atoms/Table/index.tsx
  client/src/components/atoms/Tr/index.tsx
  client/src/components/molecules/DTRManagementTable/DesktopTable.tsx
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/DTRSummaryTable/DesktopTable.tsx
  client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
  client/src/components/molecules/EmployeeManagementTable/DesktopTable.tsx
  client/src/components/molecules/EmployeeManagementTable/MobileDisclose.tsx
  client/src/components/molecules/LeaveManagementResultTable/MobileDisclose.tsx
  client/src/components/molecules/LeaveManagementResultTable/Table.tsx
  client/src/components/molecules/ListOfLeaveTable/DesktopTable.tsx
  client/src/components/molecules/ListOfLeaveTable/MobileDisclose.tsx
  client/src/components/molecules/ListOfLeaveTable/columns.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyOvertimeTable/DesktopTable.tsx
  client/src/components/molecules/MyOvertimeTable/MobileDisclose.tsx
  client/src/components/molecules/NavList/index.tsx
  client/src/components/molecules/NotificationList/NotificationItem.tsx
  client/src/components/molecules/OvertimeManagementTable/DesktopTable.tsx
  client/src/components/molecules/OvertimeManagementTable/MobileDisclose.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/templates/FadeInOut/index.tsx
  client/src/components/templates/Layout/index.tsx
  client/src/components/templates/ScheduleManagementLayout/CustomSearch.tsx
  client/src/components/templates/ScheduleManagementLayout/index.tsx
  client/src/pages/dtr-management.tsx
  client/src/pages/leave-management/leave-summary.tsx
  client/src/pages/leave-management/list-of-leave.tsx
  client/src/pages/leave-management/yearly-summary.tsx
  client/src/pages/my-daily-time-record.tsx
  client/src/pages/my-forms/atm-applications.tsx
  client/src/pages/my-forms/first-day-onboarding.tsx
  client/src/pages/my-forms/laptop-monitoring.tsx
  client/src/pages/my-forms/personal-information.tsx
  client/src/pages/my-leaves.tsx
  client/src/pages/my-overtime.tsx
  client/src/pages/notifications.tsx
  client/src/pages/overtime-management.tsx
  client/src/pages/schedule-management.tsx
  client/src/pages/sign-in.tsx
  client/src/utils/constants/animationVariants.ts
  client/src/utils/constants/dummyScheduleData.ts
  client/src/utils/types/formValues.ts
  client/src/utils/types/scheduleTypes.ts
  client/src/utils/validation/index.ts
Labels: Approved by John Roy ✅, For Code Review 💻

#127 HRIS-155 [BugTask] Apply user avatar in the DTR Management page and DTR Summary
  api/DTOs/LeaveDTO.cs
  api/DTOs/TimeEntriesSummaryDTO.cs
  api/DTOs/TimeEntryDTO.cs
  api/Schema/Queries/LeaveQuery.cs
  api/Services/LeaveService.cs
  api/Services/TimeSheetService.cs
  api/wwwroot/static/avatar/default.png
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/DTRSummaryTable/MobileDisclose.tsx
  client/src/components/molecules/DTRSummaryTable/columns.tsx
  client/src/components/molecules/ListOfLeaveTable/MobileDisclose.tsx
  client/src/components/molecules/ListOfLeaveTable/columns.tsx
  client/src/graphql/queries/leaveQueries.ts
  client/src/graphql/queries/timesheetQueries.ts
  client/src/pages/leave-management/list-of-leave.tsx
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/leaveTypes.ts
  client/src/utils/types/timeEntryTypes.ts
Labels: For Code Review 💻

#129 HRIS-130 [Markup] Create ATM Application Form
  client/src/pages/my-forms/atm-applications.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#131 HRIS-162 [BugTask] Fix: Error in My DTR status of overtime column
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
Labels: Approved and Merged ✔️

#132 HRIS-132-01 [Markup] Fix Mobile View Schedule Form, Move the buttons in the center
  client/src/components/atoms/Buttons/DayButton.tsx
  client/src/pages/my-forms/atm-applications.tsx
  client/src/pages/my-forms/personal-information.tsx
  client/src/pages/schedule-management.tsx
Labels: Approved and Merged ✔️

#133 HRIS-131 [Markup] Create Laptop Monitoring Form
  client/src/pages/my-forms/laptop-monitoring.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#135 HRIS-165 [BugTask] Fetch data in requested hours in My Overtime
  api/DTOs/MyOvertimeDTO.cs
  client/src/components/molecules/MyOvertimeTable/columns.tsx
Labels: For Code Review 💻

#138 HRIS-166 [Markup] Create Modal for Change Shift Request
  client/src/components/molecules/MyDailyTimeRecordTable/ChangeShiftRequestModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#139 HRIS-164 [FE] Integrate request for change shift functionality
  api/DTOs/UserDTO.cs
  api/Enums/InputValidationMessageEnum.cs
  api/Requests/CreateChangeShiftRequest.cs
  api/Services/ChangeShiftService.cs
  api/Services/TimeInService.cs
  api/Utils/Validation.cs
  client/src/components/molecules/MyDailyTimeRecordTable/ChangeShiftRequestModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/graphql/mutations/changeShiftMutation.ts
  client/src/graphql/queries/UserQuery.ts
  client/src/hooks/useChangeShift.ts
  client/src/utils/constants/projects.ts
  client/src/utils/constants/userPositions.ts
  client/src/utils/types/changeShiftTypes.ts
  client/src/utils/types/userTypes.ts
Labels: For Code Review 💻

#140 HRIS-161 [BE/FE] Manager Overtime Management Rework
  api/DTOs/UserDTO.cs
  api/Services/ApprovalService.cs
  api/Services/TimeInService.cs
  client/next.config.js
  client/src/components/molecules/OvertimeManagementTable/columns.tsx
  client/src/graphql/queries/UserQuery.ts
  client/src/pages/overtime-management.tsx
  client/src/pages/sign-in.tsx
  client/src/utils/constants/position.ts
  client/src/utils/types/userTypes.ts
Labels: For Code Review 💻

#143 HRIS-174 [BE] Implement approve or disapprove change shift request functionality
  api/Entities/MultiProject.cs
  api/Enums/NotificationTypeEnum.cs
  api/Requests/ApproveChangeShiftRequest.cs
  api/Schema/Mutations/ApprovalMutation.cs
  api/Schema/Mutations/ChangeShiftMutation.cs
  api/Services/ApprovalService.cs
  api/Services/ChangeShiftService.cs
  api/Services/NotificationService.cs
  api/Utils/Validation.cs
Labels: Approved by Nilo✅, For Code Review 💻

#144 HRIS-168 [Markup] Create Modal for filing a request for OT or Offset
  client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx
  client/src/components/molecules/FiledOffsetModal/index.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: Approved by Joshua 👌, For Code Review 💻

#145 HRIS-175 [FE] Integrate approve or disapprove change shift request functionality
  api/Services/ApprovalService.cs
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/mutations/changeShiftMutation.ts
  client/src/graphql/subscriptions/leaveSubscription.ts
  client/src/hooks/useChangeShift.ts
  client/src/pages/notifications.tsx
  client/src/utils/constants/dummyNotificationData.ts
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/changeShiftTypes.ts
  client/src/utils/types/notificationTypes.ts
Labels: For Code Review 💻

#148 HRIS-175-01 Fix Date in Notification Detail Modal
  api/Services/NotificationService.cs
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
Labels: For Code Review 💻

#150 HRIS-168-1 [Markup] Bugfix on AddNewOffsetModal and FileOffsetModal border error
  client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#149 HRIS-182 [FE] Integrate change schedule as an offset functionality for ESL Teacher
  client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/ChangeShiftDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/ChangeShiftResolved.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/LeaveDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/LeaveResolvedDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/OffsetScheduleDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/OvertimeDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/OvertimeResolvedDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/ResolvedDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/UndertimeDetails.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/UndertimeResolvedDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/mutations/eslOffsetMutation.ts
  client/src/graphql/queries/UserQuery.ts
  client/src/graphql/subscriptions/eslOffsetSubscription.ts
  client/src/hooks/useOffsetForESL.ts
  client/src/hooks/useUserQuery.ts
  client/src/pages/notifications.tsx
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/createLeaveHelpers.ts
  client/src/utils/interfaces/eslOffsetInterface.ts
Labels: For Code Review 💻

#152 HRIS-176 [BE] Implement approve or disapprove change offset request functionality
  api/Requests/ApproveESLChangeShiftRequest.cs
  api/Schema/Mutations/ESLChangeShiftMutation.cs
  api/Services/ApprovalService.cs
  api/Services/NotificationService.cs
  api/Utils/Validation.cs
Labels: Approved by Arden ✅, For Code Review 💻
