Repository framgia/sph-hris, pull requests merged in 2023-04, with the labels that each got.

#153 HRIS-184 [BugTask] Time in the notification menu and page are not same
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/NotificationList/NotificationItem.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/components/organisms/Header/index.tsx
Labels: Approved by Joshua 👌, For Code Review 💻

#156 HRIS-184-02 [FE] Readded Filed Offset Modal in DTR Management page
  client/src/components/molecules/DTRManagementTable/MobileDisclose.tsx
  client/src/components/molecules/DTRManagementTable/columns.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
Labels: For Code Review 💻

#155 HRIS-177 [FE] Integrate approve or disapprove change offset request functionality
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/components/molecules/NotificationPopOver/index.tsx
  client/src/graphql/mutations/eslOffsetMutation.ts
  client/src/hooks/useOffsetForESL.ts
  client/src/utils/interfaces/eslOffsetInterface.ts
Labels: For Code Review 💻

#157 HRIS-179 [BE] Implement approve or disapprove offset request filed functionality
  api/Schema/Mutations/ESLOffsetMutation.cs
  api/Services/ApprovalService.cs
  api/Services/ESLChangeShiftService.cs
  api/Services/NotificationService.cs
  api/Utils/Validation.cs
Labels: For Code Review 💻

#159 HRIS-180 [FE] Integrate approve or disapprove offset request filed functionality
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/graphql/mutations/eslOffsetMutation.ts
  client/src/hooks/useOffsetForESL.ts
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/interfaces/eslOffsetInterface.ts
Labels: Approved by Joshua 👌, Approved by Nilo✅, For Code Review 💻

#158 HRIS-183 [FE] Integrate file OT or offset request functionality
  api/DTOs/ESLOffsetDTO.cs
  api/Enums/NotificationTypeEnum.cs
  api/Schema/Queries/ESLOffsetQuery.cs
  api/Services/ESLOffsetService.cs
  client/src/components/molecules/FiledOffsetModal/FileOffsetModal.tsx
  client/src/components/molecules/FiledOffsetModal/MobileDisclose.tsx
  client/src/components/molecules/FiledOffsetModal/columns.tsx
  client/src/components/molecules/FiledOffsetModal/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/NotificationList/NotificationTypeDetails/OffsetDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/graphql/mutations/fileOffsetMutation.ts
  client/src/graphql/queries/eslFiledOffsets.ts
  client/src/graphql/subscriptions/fileOffsetSubscription.ts
  client/src/hooks/useFileOffset.ts
  client/src/hooks/useOffsetForESL.ts
  client/src/lib/queryClient.ts
  client/src/pages/_app.tsx
  client/src/pages/sign-in.tsx
  client/src/utils/constants/dummyFiledOffsetsData.ts
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/icons/WaveStyle.tsx
  client/src/utils/interfaces/fileOffsetInterface.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/myDailyTimeHelpers.ts
Labels: For Code Review 💻

#160 HRIS-185 [FE] Improve the Login button
  client/src/pages/sign-in.tsx
Labels: Approved by Joshua 👌, For Code Review 💻

#161 HRIS-183-01 [FE] Fix Notification Offset Resolved Details
  client/src/components/molecules/NotificationList/NotificationTypeDetails/OffsetResolvedDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal.tsx
  client/src/utils/constants/notificationTypes.ts
Labels: Approved by Arden ✅, For Code Review 💻

#162 HRIS-186 [BE] Implement view filed change shift for ESL and Non-ESL functionality
  api/DTOs/ChangeShiftDTO.cs
  api/DTOs/ESLChangeShiftDTO.cs
  api/DTOs/TimeEntryDTO.cs
  api/Services/TimeSheetService.cs
Labels: Approved by John Roy ✅, Approved by Joshua 👌, Approved by Nilo✅

#163 HRIS-187 [FE] Integrate view filed change shift for ESL and Non-ESL functionality
  client/src/components/molecules/InterruptionTimeEntriesModal/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/ChangeShiftRequestModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/ViewFiledChangeShiftModal/ChangeShiftDetails.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/ViewFiledChangeShiftModal/ESLChangeShiftDetails.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/ViewFiledChangeShiftModal/index.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/ChangeShiftDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/ChangeShiftResolved.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/ESLChangeShiftDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/LeaveDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/LeaveResolvedDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetResolvedDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/OffsetScheduleDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/OvertimeDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/OvertimeResolvedDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/ResolvedDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/UndertimeDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/UndertimeResolvedDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/index.tsx
  client/src/graphql/queries/timesheetQueries.ts
  client/src/hooks/useChangeShift.ts
  client/src/hooks/useOffsetForESL.ts
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/types/timeEntryTypes.ts
Labels: Approved by Nilo✅, For Code Review 💻

#166 HRIS-197 [BE] Implement display schedule functionality
  api/DTOs/EmployeeScheduleDTO.cs
  api/Enums/DaysOfTheWeekEnum.cs
  api/Program.cs
  api/Requests/EmployeeScheduleRequest.cs
  api/Schema/Queries/EmployeeScheduleQuery.cs
  api/Services/EmployeeScheduleService.cs
Labels: For Code Review 💻

#167 HRIS-192 [BE] Modify display of ESL Change Shift and Notification Approve/Disapprove Functionality
  api/DTOs/ESLOffsetDTO.cs
  api/NotificationDataClasses/ChangeShiftData.cs
  api/Services/ApprovalService.cs
  api/Services/NotificationService.cs
Labels: For Code Review 💻

#168 HRIS-198 [FE] Integrate display schedule functionality
  client/src/components/templates/ScheduleManagementLayout/index.tsx
  client/src/graphql/queries/employeeSchedule.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/pages/schedule-management.tsx
  client/src/utils/types/employeeScheduleTypes.ts
Labels: For Code Review 💻

#170 HRIS-198-1 [FE] Bugfix on new day always starts on monday
  client/src/pages/schedule-management.tsx
  client/src/utils/constants/weekDays.ts
  client/src/utils/types/weekDayTypes.ts
Labels: For Code Review 💻

#169 HRIS-193 [BE] Implement Create Schedule Functionality
  api/Enums/ErrorMessageEnum.cs
  api/Enums/InputValidationMessageEnum.cs
  api/Enums/SuccessMessageEnum.cs
  api/Program.cs
  api/Requests/CreateEmployeeScheduleRequest.cs
  api/Requests/EmployeeScheduleRequest.cs
  api/Requests/WorkingDayTimesRequest.cs
  api/Schema/Mutations/EmployeeScheduleMutation.cs
  api/Services/EmployeeScheduleService.cs
  api/Utils/Validation.cs
Labels: For Code Review 💻

#171 HRIS-199 [FE] Integrate Modify ESL Change Shift Functionality
  api/Services/ESLOffsetService.cs
  client/package-lock.json
  client/package.json
  client/src/components/molecules/MyDailyTimeRecordTable/AddNewOffsetModal.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/DesktopTable.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/MobileDisclose.tsx
  client/src/components/molecules/MyDailyTimeRecordTable/columns.tsx
  client/src/graphql/queries/unusedESLOffsets.ts
  client/src/hooks/useUnusedESLOffset.ts
  client/src/pages/_app.tsx
  client/src/pages/my-forms/laptop-monitoring.tsx
  client/src/pages/sign-in.tsx
  client/src/utils/createLeaveHelpers.ts
  client/src/utils/interfaces/eslOffsetInterface.ts
  client/src/utils/interfaces/unusedELSOffsetInterface.ts
  client/src/utils/myDailyTimeHelpers.ts
  client/src/utils/next-progress.tsx
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#172 HRIS-200 [FE] Integrate the modified display of ESL Change Shift and Notification Approve/Disapprove Functionality
  client/src/components/molecules/NotificationList/ViewDetailsModal/ESLChangeShiftDetails.tsx
  client/src/components/molecules/NotificationList/ViewDetailsModal/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/pages/notifications.tsx
  client/src/utils/constants/notificationTypes.ts
  client/src/utils/interfaces/eslOffsetInterface.ts
  client/src/utils/interfaces/index.tsx
  client/src/utils/types/notificationTypes.ts
Labels: For Code Review 💻

#173 HRIS-195 [BE] Implement edit schedule details functionality
  api/Enums/ErrorMessageEnum.cs
  api/Enums/InputValidationMessageEnum.cs
  api/Enums/SuccessMessageEnum.cs
  api/Requests/UpdateEmployeeScheduleRequest.cs
  api/Schema/Mutations/EmployeeScheduleMutation.cs
  api/Services/EmployeeScheduleService.cs
  api/Utils/Validation.cs
Labels: Approved by Arden ✅, For Code Review 💻

#174 HRIS-194 [FE] Integrate Create Employee Schedule Functionality
  client/src/graphql/mutations/employeeScheduleMutation.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/pages/schedule-management.tsx
  client/src/utils/constants/weekDays.ts
  client/src/utils/types/employeeScheduleTypes.ts
Labels: For Code Review 💻

#175 HRIS-201 [FE] Remove Error in DTRManagement Page Console
  client/src/pages/dtr-management.tsx
Labels: For Code Review 💻

#176 HRIS-196 [FE] Integrate edit schedule functionality
  client/src/graphql/mutations/employeeScheduleMutation.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/pages/schedule-management.tsx
  client/src/utils/types/employeeScheduleTypes.ts
Labels: Approved by Joshua 👌, Approved by Nilo✅

#178 HRIS-196-1 [FE] Allow Edit Cancel
  client/src/pages/schedule-management.tsx
Labels: For Code Review 💻

#180 HRIS-208 [Markup] Create Schedule Modal
  client/src/components/atoms/TabLink/index.tsx
  client/src/components/molecules/ViewScheduleMembersModal/MemberList.tsx
  client/src/components/molecules/ViewScheduleMembersModal/index.tsx
  client/src/components/templates/ModalTemplate/ModalHeader.tsx
  client/src/pages/schedule-management.tsx
  client/src/utils/constants/dummyScheduleMembers.ts
  client/src/utils/interfaces/scheduleMemberInterface.ts
Labels: For Code Review 💻

#181 HRIS-211 [Markup] Create Modal for adding employees to a schedule
  client/src/components/molecules/ViewScheduleMembersModal/AddScheduleMembersModal.tsx
  client/src/components/molecules/ViewScheduleMembersModal/index.tsx
  client/src/components/templates/ModalTemplate/ModalHeader.tsx
  client/src/utils/helpers/scheduleMemberHelpers.ts
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#182 HRIS-210 [FE] Implement UI feature to display list of employees assigned to a selected schedule
  api/DTOs/EmployeeScheduleDTO.cs
  api/Services/EmployeeScheduleService.cs
  client/src/components/molecules/ViewScheduleMembersModal/index.tsx
  client/src/graphql/queries/employeeSchedule.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/pages/schedule-management.tsx
  client/src/utils/constants/fetchStatus.ts
  client/src/utils/types/employeeScheduleTypes.ts
Labels: For Code Review 💻

#184 HRIS-216 [Markup] Create Modal for Re-assigning an employee
  client/src/components/molecules/ViewScheduleMembersModal/MemberList.tsx
  client/src/components/molecules/ViewScheduleMembersModal/ReassignMemberScheduleModal.tsx
  client/src/components/templates/ModalTemplate/ModalHeader.tsx
  client/src/components/templates/ScheduleManagementLayout/index.tsx
  client/src/graphql/queries/employeeSchedule.ts
  client/src/pages/schedule-management.tsx
  client/src/utils/helpers/scheduleMemberHelpers.ts
  client/src/utils/types/employeeScheduleTypes.ts
  client/src/utils/types/formValues.ts
  client/src/utils/validation/index.ts
Labels: For Code Review 💻

#183 HRIS-214 [BE] Implement add member to schedule functionality
  api/Enums/ErrorMessageEnum.cs
  api/Enums/InputValidationMessageEnum.cs
  api/Enums/SuccessMessageEnum.cs
  api/Requests/AddMemberToScheduleRequest.cs
  api/Schema/Mutations/EmployeeScheduleMutation.cs
  api/Services/EmployeeScheduleService.cs
  api/Utils/Validation.cs
Labels: For Code Review 💻

#185 HRIS-222 [BE] Implement remove schedule functionality
  api/Enums/ErrorMessageEnum.cs
  api/Enums/SuccessMessageEnum.cs
  api/Requests/DeleteEmployeeScheduleRequest.cs
  api/Schema/Mutations/EmployeeScheduleMutation.cs
  api/Services/EmployeeScheduleService.cs
  api/Utils/Validation.cs
Labels: For Code Review 💻

#186 HRIS-219 [BE] Implement search employee functionality
  api/Requests/SearchEmployeesByScheduleRequest.cs
  api/Schema/Queries/EmployeeScheduleQuery.cs
  api/Services/EmployeeScheduleService.cs
Labels: For Code Review 💻

#187 HRIS-223 [FE] Integrate remove schedule functionality
  client/src/components/templates/ScheduleManagementLayout/index.tsx
  client/src/graphql/mutations/employeeScheduleMutation.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/utils/types/employeeScheduleTypes.ts
Labels: For Code Review 💻

#188 HRIS-215 [FE] Integrate add member to schedule functionality
  api/Enums/SuccessMessageEnum.cs
  client/src/components/molecules/ViewScheduleMembersModal/AddScheduleMembersModal.tsx
  client/src/components/molecules/ViewScheduleMembersModal/index.tsx
  client/src/graphql/mutations/employeeScheduleMutation.ts
  client/src/graphql/queries/UserQuery.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/utils/helpers/scheduleMemberHelpers.ts
  client/src/utils/types/employeeScheduleTypes.ts
  client/src/utils/types/userTypes.ts
Labels: For Code Review 💻

#189 HRIS-220 [FE] Integrate search employee functionality
  client/src/components/molecules/ViewScheduleMembersModal/index.tsx
  client/src/graphql/queries/employeeSchedule.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/utils/types/employeeScheduleTypes.ts
Labels: For Code Review 💻

#190 HRIS-217 [BE] Implement re-assign employee schedule functionality
  api/Enums/SuccessMessageEnum.cs
  api/Requests/UpdateMemberScheduleRequest.cs
  api/Schema/Mutations/EmployeeScheduleMutation.cs
  api/Services/EmployeeScheduleService.cs
  api/Utils/Validation.cs
Labels: For Code Review 💻

#191 HRIS-218 [FE] Integrate re-assign employee schedule functionality
  client/src/components/molecules/ViewScheduleMembersModal/MemberList.tsx
  client/src/components/molecules/ViewScheduleMembersModal/ReassignMemberScheduleModal.tsx
  client/src/graphql/mutations/employeeScheduleMutation.ts
  client/src/hooks/useEmployeeSchedule.ts
  client/src/utils/types/employeeScheduleTypes.ts
Labels: For Code Review 💻
